=== hanbioinformatica/owe8a/JSXMLJSON/static/XML/protein/protein.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
                    Sample XML Schema for representing Protein data.
                </xs:documentation>
    </xs:annotation>
    <xs:element name="protein_set">
        <xs:annotation>
            <xs:documentation>
                            A protein set can have one or more protein elements.
                        </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:restriction base="xs:anyType">
                    <xs:sequence>
                        <xs:element ref="protein" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:restriction>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="protein">
        <xs:annotation>
            <xs:documentation>Main Protein Element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:restriction base="xs:anyType">
                    <xs:sequence>
                        <xs:element name="accession" type="xs:string"/>
                        <xs:element name="entry_name" type="xs:string"/>
                        <xs:element name="protein_name" type="xs:string"/>
                        <xs:element name="gene_name" type="xs:string"
                                                    maxOccurs="10"/>
                        <xs:element ref="organism"/>
                        <xs:element ref="cross_reference" minOccurs="0"
                                                    maxOccurs="unbounded"/>
                        <xs:element name="comment" type="xs:string" minOccurs="0"
                                                    maxOccurs="unbounded"/>
                        <xs:element name="keyword" type="xs:string" minOccurs="0"
                                                    maxOccurs="10"/>
                    </xs:sequence>
                </xs:restriction>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="organism">
        <xs:annotation>
            <xs:documentation>
                            Organism for referencing NCBI Taxonomy ID
                        </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="taxonomy_id" type="xs:integer"
                                            use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="cross_reference">
        <xs:annotation>
            <xs:documentation>Cross refererence to other database.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:restriction base="xs:anyType">
                    <xs:attribute name="database" type="xs:string" use="required"/>
                    <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:restriction>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hanbioinformatica/owe8a/JSXMLJSON/static/XML/protein/protein.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="protein.xsl"?>
<protein_set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="protein.xsd">
        
    <protein>
        <accession>P26954</accession>
        <entry_name>IL3B_MOUSE</entry_name>
        <protein_name>Interleukin-3 receptor class II
            beta chain [Precursor]
        </protein_name>
        <gene_name>CSF2RB2</gene_name>
        <gene_name>AI2CA</gene_name>
        <gene_name>IL3RB2</gene_name>
        <gene_name>IL3R</gene_name>
       
        <organism taxonomy_id="10090">Mus musculus</organism>
        <cross_reference database="EMBL" id="M29855"/>
        <cross_reference database="EMBL" id="AAA39295"/>
        <cross_reference database="PIR" id="A40091"/>

        <cross_reference database="MGD" id="MGI:1339760"/>
        <cross_reference database="InterPro" id="IPR002996"/>
        <comment>FUNCTION: IN MOUSE THERE ARE TWO CLASSES OF
          HIGH-AFFINITY IL-3 RECEPTORS. ONE CONTAINS THIS IL-3-
          SPECIFIC BETA CHAIN AND THE OTHER CONTAINS THE BETA
          CHAIN ALSO SHARED BY HIGH-AFFINITY IL-5 AND GM-CSF
          RECEPTORS.</comment>
        <comment>SUBUNIT: Heterodimer of an alpha
        and a beta chain.</comment>
        <comment>SUBCELLULAR LOCATION: Type I
        membrane protein.</comment>
        <comment>SIMILARITY: BELONGS TO THE CYTOKINE
        FAMILY OF RECEPTORS.
        </comment>
        <keyword>Receptor</keyword>
        <keyword>Glycoprotein</keyword>
        <keyword>Signal</keyword>
    </protein>
</protein_set>
